query($owner: String!, $name: String!, $number: Int!) {
  repository(owner: $owner, name: $name) {
    pullRequest(number: $number) {
      id
      __typename
      number
      title
      merged
      closed
    }
  }
}
